<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clients = [
            ['nom' => 'SITEL (ACTICALL)', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'SOTHEMA', 'secteur_activite_id' => 2, 'active' => 1],
            ['nom' => 'AFRIC-PHAR', 'secteur_activite_id' => 2, 'active' => 1],
            ['nom' => 'SAFRAN NACELLE (AIRCELLE)', 'secteur_activite_id' => 3, 'active' => 1],
            ['nom' => 'AKZO', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'ATLAS ONLINE', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'B 2 S MAARIF BEN OMAR ', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'B 2 S YAACOUB MANSOUR', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'BAYER', 'secteur_activite_id' => 2, 'active' => 1],
            ['nom' => 'BIM ADM CENTRAL ', 'secteur_activite_id' => 5, 'active' => 1],
            ['nom' => 'BIM STORES D', 'secteur_activite_id' => 5, 'active' => 1],
            ['nom' => 'BIMO', 'secteur_activite_id' => 5, 'active' => 1],
            ['nom' => 'HENRYS D', 'secteur_activite_id' => 6, 'active' => 1],
            ['nom' => 'HENRYS', 'secteur_activite_id' => 6, 'active' => 1],
            ['nom' => 'BRASSERIE', 'secteur_activite_id' => 6, 'active' => 1],
            ['nom' => 'BRINKS', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'C.M DEVELOPPEMENT', 'secteur_activite_id' => 3, 'active' => 1],
            ['nom' => 'CALL ONE (TOTAL CALL)', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'CROWN (CARNAUD)', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'CEMA', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'C.NOOR', 'secteur_activite_id' => 7, 'active' => 1],
            ['nom' => 'CFCA', 'secteur_activite_id' => 8, 'active' => 1],
            ['nom' => 'SAM (CREUZET)', 'secteur_activite_id' => 3, 'active' => 1],
            ['nom' => 'DILIPATE', 'secteur_activite_id' => 6, 'active' => 1],
            ['nom' => 'DELL', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'DISWAY', 'secteur_activite_id' => 9, 'active' => 1],
            ['nom' => 'DOMAINES AGRICOLES (DOMAINE R)', 'secteur_activite_id' => 6, 'active' => 1],
            ['nom' => 'EXCELSA', 'secteur_activite_id' => 7, 'active' => 1],
            ['nom' => 'FIRST-THERM', 'secteur_activite_id' => 9, 'active' => 1],
            ['nom' => 'FRANCE NEON', 'secteur_activite_id' => 7, 'active' => 1],
            ['nom' => 'G.F.I', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'GROUPE PREMIUM', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'IMA',  'secteur_activite_id' => 10, 'active' => 1],
            ['nom' => 'MAISONDELAVIE', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'LABORATOIRE NOVOVET', 'secteur_activite_id' => 2, 'active' => 1],
            ['nom' => 'SIRAIL MAROC (LIA TECH)', 'secteur_activite_id' => 7, 'active' => 1],
            ['nom' => 'MAPHAR A.S (MAPHAR.C)', 'secteur_activite_id' => 2, 'active' => 1],
            ['nom' => 'MAPHAR.Z', 'secteur_activite_id' => 2, 'active' => 1],
            ['nom' => 'MARBAR CHIMIE', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'MARJANE AS', 'secteur_activite_id' => 5, 'active' => 1],
            ['nom' => 'MARJANE CALIFORNIE', 'secteur_activite_id' => 5, 'active' => 1],
            ['nom' => 'MARJANE ENTREPOT', 'secteur_activite_id' => 9, 'active' => 1],
            ['nom' => 'MARJANE HAY', 'secteur_activite_id' => 5, 'active' => 1],
            ['nom' => 'MARJANE MOROCCO MALL', 'secteur_activite_id' => 5, 'active' => 1],
            ['nom' => 'STELIA AEROSPACE (M.AVIATION)',  'secteur_activite_id' => 10, 'active' => 1],
            ['nom' => 'MATIS', 'secteur_activite_id' => 9, 'active' => 1],
            ['nom' => 'MC DONALDS', 'secteur_activite_id' => 6, 'active' => 1],
            ['nom' => 'MEDITEL', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'NEXANS',  'secteur_activite_id' => 12, 'active' => 1],
            ['nom' => 'SOTHEMA AIN SEBAA (NOVARTIS)', 'secteur_activite_id' => 2, 'active' => 1],
            ['nom' => 'O.G.E', 'secteur_activite_id' => 9, 'active' => 1],
            ['nom' => 'SOTREG EMBARQUEMENT CASABLANCA', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'OCP SIEGE', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'P.TEXAS', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'MAJOREL  MARSA', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'PHONE SOLEIL', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'MAJOREL   PALMIER', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'PRIMARIOS', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'PRIMARI.D', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'PROMAGHREB (PROMAGHR)',  'secteur_activite_id' => 12, 'active' => 1],
            ['nom' => 'PUBLIDAY', 'secteur_activite_id' => 7, 'active' => 1],
            ['nom' => 'RAM Piste',  'secteur_activite_id' => 13, 'active' => 1],
            ['nom' => 'CASA AERO', 'secteur_activite_id' => 3, 'active' => 1],
            ['nom' => 'RAM ANF',  'secteur_activite_id' => 13, 'active' => 1],
            ['nom' => 'RAM BRIGAD',  'secteur_activite_id' => 13, 'active' => 1],
            ['nom' => 'RAM EQUIPAGE',  'secteur_activite_id' => 13, 'active' => 1],
            ['nom' => 'RAM ESCAL',  'secteur_activite_id' => 13, 'active' => 1],
            ['nom' => 'RAM HOT', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'RAM NS',  'secteur_activite_id' => 13, 'active' => 1],
            ['nom' => 'S2M', 'secteur_activite_id' => 7, 'active' => 1],
            ['nom' => 'SERMP', 'secteur_activite_id' => 3, 'active' => 1],
            ['nom' => 'SERVIER.M', 'secteur_activite_id' => 2, 'active' => 1],
            ['nom' => 'CABIND BER', 'secteur_activite_id' => 8, 'active' => 1],
            ['nom' => 'CABIND BER-CASA', 'secteur_activite_id' => 8, 'active' => 1],
            ['nom' => 'CABIND CASA-BER',  'secteur_activite_id' => 12, 'active' => 1],
            ['nom' => 'STCR.AT', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'STCR.D', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'STCR TOURISME', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'THESEE MAROC', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'TOTAL CALL', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'TRACTAFRIC (TRACTAF)', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'USINE ELECTRIQUE', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'CASA TRAM', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'MAJOREL  CASANEARSHORE', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'KENZI TOWER HOTEL', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'ARAMEX', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'CABIND AIN HARROUDA',  'secteur_activite_id' => 12, 'active' => 1],
            ['nom' => 'SPIRIT AEROSYSTEMS (BOMBARDIER)',  'secteur_activite_id' => 10, 'active' => 1],
            ['nom' => 'CABIND A.SEBAA',  'secteur_activite_id' => 12, 'active' => 1],
            ['nom' => 'CMGP', 'secteur_activite_id' => 9, 'active' => 1],
            ['nom' => 'CHRONOPOST', 'secteur_activite_id' => 9, 'active' => 1],
            ['nom' => 'BIM STORES SITE BOUSKOURA', 'secteur_activite_id' => 7, 'active' => 1],
            ['nom' => 'LABORATOIRE PHARMA5', 'secteur_activite_id' => 2, 'active' => 1],
            ['nom' => 'CONFETEX ALBO', 'secteur_activite_id' => 7, 'active' => 1],
            ['nom' => 'LITHO TYPO MAROCAINE', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'LAPROPHAN site Hay Mohemmadi ', 'secteur_activite_id' => 2, 'active' => 1],
            ['nom' => 'LAPROPHAN site Ain sebaa', 'secteur_activite_id' => 2, 'active' => 1],
            ['nom' => 'CAPGEMINI', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'INDUSTRIE ALIMENTAIRE LA FONDA', 'secteur_activite_id' => 9, 'active' => 1],
            ['nom' => 'NSE AERO MAROC',  'secteur_activite_id' => 10, 'active' => 1],
            ['nom' => 'SIMRA MAROC', 'secteur_activite_id' => 3, 'active' => 1],
            ['nom' => 'MARJANE HOLDING SIEGE SIDI MAAROUF', 'secteur_activite_id' => 5, 'active' => 1],
            ['nom' => 'PROMACAB.',  'secteur_activite_id' => 12, 'active' => 1],
            ['nom' => 'CABLAGE INOV',  'secteur_activite_id' => 10, 'active' => 1],
            ['nom' => 'MARJANE SIDI OTHMANE', 'secteur_activite_id' => 5, 'active' => 1],
            ['nom' => 'NP MOROCCO  ',  'secteur_activite_id' => 12, 'active' => 1],
            ['nom' => 'LBOS MOROCCO', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'COMPOSITE INDUSTRIE MAROC SITE 2', 'secteur_activite_id' => 7, 'active' => 1],
            ['nom' => 'ELECTROPLANET SIDI OTHMAN', 'secteur_activite_id' => 5, 'active' => 1],
            ['nom' => 'LABORATOIRES BOTTU', 'secteur_activite_id' => 2, 'active' => 1],
            ['nom' => 'ACAM (AEROLIA)',  'secteur_activite_id' => 10, 'active' => 1],
            ['nom' => 'LEADER FOOD', 'secteur_activite_id' => 6, 'active' => 1],
            ['nom' => 'EATON INDUSTRIES MOROCCO ', 'secteur_activite_id' => 9, 'active' => 1],
            ['nom' => 'PROMACAB site 2',  'secteur_activite_id' => 12, 'active' => 1],
            ['nom' => 'PHARMA 5 - HAD SOUALEM', 'secteur_activite_id' => 2, 'active' => 1],
            ['nom' => 'STATION MAGRUMES', 'secteur_activite_id' => 6, 'active' => 1],
            ['nom' => 'IMA - BOMBARDIER',  'secteur_activite_id' => 10, 'active' => 1],
            ['nom' => 'STATION MAGRUMES / SCAD ADMINISTRATION', 'secteur_activite_id' => 6, 'active' => 1],
            ['nom' => 'MANAR', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'LES CAFES DUBOIS', 'secteur_activite_id' => 9, 'active' => 1],
            ['nom' => 'SOTREG EL JADIDA',  'secteur_activite_id' => 14, 'active' => 1],
            ['nom' => 'BIM STORES MOHAMMEDIA', 'secteur_activite_id' => 5, 'active' => 1],
            ['nom' => 'COMPOSITE INDUSTRIE MAROC SITE 3', 'secteur_activite_id' => 7, 'active' => 1],
            ['nom' => 'MARJANE IBN TACHFINE', 'secteur_activite_id' => 5, 'active' => 1],
            ['nom' => 'AEROTECHNIC INDUSTRIES',  'secteur_activite_id' => 13, 'active' => 1],
            ['nom' => 'HEXCEL COMPOSITES',  'secteur_activite_id' => 10, 'active' => 1],
            ['nom' => 'SED (SAGEM)', 'secteur_activite_id' => 3, 'active' => 1],
            ['nom' => 'S.O.T.R.E.G  (Youssoufia)',  'secteur_activite_id' => 14, 'active' => 1],
            ['nom' => 'MITSUBA MOROCCO ',  'secteur_activite_id' => 10, 'active' => 1],
            ['nom' => 'ADF TECHNOLOGIES',  'secteur_activite_id' => 10, 'active' => 1],
            ['nom' => 'ISP INDUS MAROC', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'CM MECANIQUE', 'secteur_activite_id' => 3, 'active' => 1],
            ['nom' => 'SOTREG SAFI',  'secteur_activite_id' => 14, 'active' => 1],
            ['nom' => 'ELECTROPRINT', 'secteur_activite_id' => 7, 'active' => 1],
            ['nom' => 'HUMANIA BPO MOROCCO', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'SOTREG SITE KHOURIBGA',  'secteur_activite_id' => 14, 'active' => 1],
            ['nom' => 'GLOBAL ENGINES', 'secteur_activite_id' => 7, 'active' => 1],
            ['nom' => 'BOUYGUES CONSTRUCTION IT MAROC', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'COMPOSITE INDUSTRIE MAROC SITE 4', 'secteur_activite_id' => 7, 'active' => 1],
            ['nom' => 'SOCIETE MAROCAINE DES TABACS', 'secteur_activite_id' => 6, 'active' => 1],
            ['nom' => 'FROMAGERIES BEL MOHAMMEDIA', 'secteur_activite_id' => 6, 'active' => 1],
            ['nom' => 'CASA TRAM T2', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'CASA TRAM STATION IBN TACHFINE', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'MARJANE HOLDING - MARINA', 'secteur_activite_id' => 5, 'active' => 1],
            ['nom' => 'BZ AERO', 'secteur_activite_id' => 7, 'active' => 1],
            ['nom' => 'ACIMA', 'secteur_activite_id' => 7, 'active' => 1],
            ['nom' => 'SOTREG BENGUERIR',  'secteur_activite_id' => 14, 'active' => 1],
            ['nom' => 'RAM PN',  'secteur_activite_id' => 13, 'active' => 1],
            ['nom' => 'CFCA SITE 2 UAP9', 'secteur_activite_id' => 8, 'active' => 1],
            ['nom' => 'MARJANE MARKET DAR BOUAZZA', 'secteur_activite_id' => 5, 'active' => 1],
            ['nom' => 'COMDATA SITE MARINA', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'ELECTROPLANET DAR BOUAZZA', 'secteur_activite_id' => 5, 'active' => 1],
            ['nom' => 'CASA TRAM LISSASFA', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'RAM HANDLING',  'secteur_activite_id' => 13, 'active' => 1],
            ['nom' => 'HUMANIA CASANEARSHORE', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'PARIS TEXAS OUKACHA', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'COMPOSITE INDUSTRIE MAROC SITE 5', 'secteur_activite_id' => 7, 'active' => 1],
            ['nom' => 'SATYS SEALING § PAINTING ',  'secteur_activite_id' => 10, 'active' => 1],
            ['nom' => 'ILLIANCE (IMEPSA)', 'secteur_activite_id' => 7, 'active' => 1],
            ['nom' => 'ORCHESTRA', 'secteur_activite_id' => 5, 'active' => 1],
            ['nom' => 'KRONOSOL', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'SEWS CABIND BERRECHID SITE 2', 'secteur_activite_id' => 8, 'active' => 1],
            ['nom' => 'Deva Pharmaceutique', 'secteur_activite_id' => 2, 'active' => 1],
            ['nom' => 'ACIMA DAR BOUAZZA EL MENZAH', 'secteur_activite_id' => 5, 'active' => 1],
            ['nom' => 'FIGEACAERO MAROC', 'secteur_activite_id' => 3, 'active' => 1],
            ['nom' => 'EMID', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'ARAMEX SITE NOUACEUR', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'ESNAPHARM', 'secteur_activite_id' => 2, 'active' => 1],
            ['nom' => 'STCR TRANURB ', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'EMID SITE BOUSKOURA', 'secteur_activite_id' => 7, 'active' => 1],
            ['nom' => 'LOGISOLUTION', 'secteur_activite_id' => 6, 'active' => 1],
            ['nom' => 'SABCA MAROC', 'secteur_activite_id' => 3, 'active' => 1],
            ['nom' => 'SDAMA',  'secteur_activite_id' => 12, 'active' => 1],
            ['nom' => 'NATUREX MAROC', 'secteur_activite_id' => 3, 'active' => 1],
            ['nom' => 'ARROW ECS SUPPORT CENTER MOROCCO', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'UMPM', 'secteur_activite_id' => 3, 'active' => 1],
            ['nom' => 'MARJANE BOUSKOURA ', 'secteur_activite_id' => 5, 'active' => 1],
            ['nom' => 'STCR', 'secteur_activite_id' => 15, 'active' => 1],
            ['nom' => 'SWING WINDS', 'secteur_activite_id' => 8, 'active' => 1],
            ['nom' => 'BHNS ( Bus way ) SITE LAHRAOUIN', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'BHNS ( Bus way) SITE OULAD AZZOUZ', 'secteur_activite_id' => 1, 'active' => 1],
            ['nom' => 'COLIBRI SERVICES', 'secteur_activite_id' => 4, 'active' => 1],
            ['nom' => 'MARJANE MALL MOHAMADIA ',  'secteur_activite_id' => 11, 'active' => 1],
            ['nom' => 'ADIMA AEROPACE ',  'secteur_activite_id' => 10, 'active' => 1],
            ['nom' => 'RAM NS NORMAL',  'secteur_activite_id' => 13, 'active' => 1],
            ['nom' => 'PROMACAB CASA-BERRECHID',  'secteur_activite_id' => 12, 'active' => 1],
        ];
        DB::table('clients')->insert($clients);
    }
}
